wisteria:
  modules:
    basePackages: org.wisteria.zk
  app:
    basePackage: org.wisteria.zk

#thymeleaf start
# cache: false表示开发时关闭缓存,不然没法看到实时页面
spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
#thymeleaf end